spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sample
        username: postgres
        password: postgres
        
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
        
security.basic.enabled: false
